### ISSUE TITLE
Updates to dev documentation

### ISSUE THREAD

**Issue by jiridanek** [red-hat-data-services/ods-ci#1385]
```
[jdanek] ods-ci pre-commit; I suggest we merge it and ask volunteers to enable it and report back
https://github.com/red-hat-data-services/ods-ci/pull/1341
[jgarciao] Looking at the [rh-pre-commit Readme](https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools/-/blob/main/rh-pre-commit/README.md) it is possible to use rh-multi-pre-commit to install multiple pre-commit hooks in their projects (I haven’t tested it)
```

* https://github.com/red-hat-data-services/ods-ci/pull/1351
* https://github.com/red-hat-data-services/ods-ci/pull/1337

## Todo

* [ ] Remove notes about black, isort, explain ruff
* [ ] Explain how to setup vs code project with pylance and robot support (we have private docs for this)
* [ ] Instructions for pre-commit
